### ISSUE TITLE
Summon Properties

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/TrinityCore#41]
Essentially most of the hardcoded nonsense for summons / pets should actually be handled by these summon properties. They need implementing properly and the hacks ripping out. This is relatively complex but might be possible to do one by one. For a long time these weren't defined or known properly but it leaked with TBC Classic. These are the same names Blizzard use and we can generally infer usage but each is worth a discussion. Once info is found a seperate issue for each will be opened.

- [ ] ATTACK_SUMMONER                 0x00000001     /// @todo: NYI 75 spells in 3.0.3, something unfriendly
- [ ] ASSIST_COMBAT_SUMMON            0x00000002     /// @todo: NYI 616 spells in 3.0.3, something friendly
- [ ] USE_LEVEL_OFFSET                0x00000004     /// @todo: NYI 22 spells in 3.0.3, no idea...
- [ ] DESPAWN_ON_SUMMONER_DEATH       0x00000008     /// @todo: NYI 49 spells in 3.0.3, some mounts
- [x] ONLY_VISIBLE_TO_SUMMONER        0x00000010     // 25 spells in 3.0.3, quest related?
- [ ] CANNOT_DISMISS_PET              0x00000020     /// @todo: NYI 0 spells in 3.3.5, unused
- [ ] USE_DEMON_TIMEOUT               0x00000040     /// @todo: NYI 12 spells in 3.0.3, no idea
- [ ] UNLIMITED_SUMMONS               0x00000080     /// @todo: NYI 4 spells in 3.0.3, no idea
- [ ] USE_CREATURE_LEVEL              0x00000100     /// @todo: NYI 51 spells in 3.0.3, no idea, many quest related
- [ ] JOIN_SUMMONER_SPAWN_GROUP       0x00000200     /// @todo: NYI 51 spells in 3.0.3, something defensive
- [ ] DO_NOT_TOGGLE                   0x00000400     /// @todo: NYI 3 spells, requires something near?
- [ ] DESPAWN_WHEN_EXPIRED            0x00000800     /// @todo: NYI 30 spells in 3.0.3, no idea
- [ ] USE_SUMMONER_FACTION            0x00001000     /// @todo: NYI Lightwell, Jeeves, Gnomish Alarm-o-bot, Build vehicles(wintergrasp)
- [ ] DO_NOT_FOLLOW_MOUNTED_SUMMONER  0x00002000     /// @todo: NYI Guides, player follows
- [ ] SAVE_PET_AUTOCAST               0x00004000     /// @todo: NYI Force of Nature, Shadowfiend, Feral Spirit, Summon Water Elemental
- [ ] IGNORE_SUMMONER_PHASE           0x00008000     /// @todo: NYI Light/Dark Bullet, Soul/Fiery Consumption, Twisted Visage, Twilight Whelp. Phase related?

They are defined here: https://github.com/Project-Epoch/TrinityCore/blob/epoch-core/src/server/shared/DataStores/DBCEnums.h#L413
